os: Visual Studio 2015
platform: x64

environment:
  matrix:
  - configuration: Release

clone_depth: 1

init:
  - git config --global core.autocrlf input

branches:
  only:
    - master

cache:
    - C:\projects\mapbox-gl-native\mason_packages

install:
  - mkdir build
  - cd build
  - appveyor DownloadFile https://releases.llvm.org/5.0.1/LLVM-5.0.1-win64.exe
  - LLVM-5.0.1-win64.exe /S /D=C:\LLVM-5.0.1
  - appveyor DownloadFile https://cmake.org/files/v3.10/cmake-3.10.1-win64-x64.zip
  - 7z x cmake-3.10.1-win64-x64.zip -oC:\

before_build:
  - set PATH=C:\LLVM-5.0.1\msbuild-bin;%PATH%
  - set PATH=C:\cmake-3.10.1-win64-x64\bin;%PATH%

build_script:
  - cmake -G "Visual Studio 14 2015 Win64" -T LLVM-vs2014 -DMBGL_PLATFORM=qt -DWITH_QT_DECODERS=ON -DWITH_QT_I18N=ON -DWITH_TESTS=OFF -DCMAKE_PREFIX_PATH="C:\Qt\5.7\msvc2015_64\lib\cmake" C:\projects\mapbox-gl-native & exit 0
  - cmake --build . --config Release --target qmapboxgl -- /m

after_build:
  - mkdir qmapboxgl
  - mkdir qmapboxgl\lib
  - mkdir qmapboxgl\include
  - copy Release\qmapboxgl.* qmapboxgl\lib
  - copy %APPVEYOR_BUILD_FOLDER%\platform\qt\include\* qmapboxgl\include
  - 7z a qmapboxgl-%APPVEYOR_REPO_COMMIT%.zip qmapboxgl

artifacts:
  - path: build\qmapboxgl-%APPVEYOR_REPO_COMMIT%.zip
    name: QMapboxGL

test: off
